services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Patika123."
      ACCEPT_EULA: "Y"
    ports:
      - 1401:1433

  redis:
    image: redis
    ports:
      - 6379:6379

  auth-server:
    build:
      context: .
      target: final
    restart: always
    ports:
      - 8080:8080