// <auto-generated />
using System;
using Framework.Test.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Framework.Test.API.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20240114192324_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Framework.Test.API.Models.CachableTestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CachableTestModels");
                });

            modelBuilder.Entity("Framework.Test.API.Models.SqlTestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SqlTestModels");
                });

            modelBuilder.Entity("Framework.Test.API.Models.SqlTestRelationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SqlTestRelationModels");
                });

            modelBuilder.Entity("RelationJoinTable", b =>
                {
                    b.Property<int>("SqlTestModelsId")
                        .HasColumnType("int");

                    b.Property<int>("SqlTestRelationModelsId")
                        .HasColumnType("int");

                    b.HasKey("SqlTestModelsId", "SqlTestRelationModelsId");

                    b.HasIndex("SqlTestRelationModelsId");

                    b.ToTable("RelationJoinTable");
                });

            modelBuilder.Entity("Framework.Test.API.Models.CachableTestModel", b =>
                {
                    b.OwnsMany("Framework.Test.API.Models.CachableTestChildModel", "Childs", b1 =>
                        {
                            b1.Property<int>("CachableTestModelId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CachableTestModelId", "Id");

                            b1.ToTable("CachableTestChildModel");

                            b1.WithOwner()
                                .HasForeignKey("CachableTestModelId");
                        });

                    b.Navigation("Childs");
                });

            modelBuilder.Entity("RelationJoinTable", b =>
                {
                    b.HasOne("Framework.Test.API.Models.SqlTestModel", null)
                        .WithMany()
                        .HasForeignKey("SqlTestModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Framework.Test.API.Models.SqlTestRelationModel", null)
                        .WithMany()
                        .HasForeignKey("SqlTestRelationModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
